### ISSUE TITLE
Would be great if code was available

### ISSUE THREAD

**Issue by carpdm** [mileyan/Pseudo_Lidar_V2#1]
Hi,

I am interested of your work, and being looking forward of the code, can you tell us when to release the code?

many thanks.

**Comment by DeepBrainsMe** [comment]
Hello,will you opensource in fews days?

**Comment by abhigoku10** [comment]
@DeepBrainsMe when can we expect the paper and code

**Comment by xy-guo** [comment]
When will the code be released?

**Comment by mileyan** [comment]
Please check the code.
