### ISSUE TITLE
checkpoint.pth.tar

### ISSUE THREAD

**Issue by Baboom-l** [mileyan/Pseudo_Lidar_V2#17]
I can not find checkpoint.pth.tar，and What is the function of checkpoint in  inferenceing

**Comment by lhx0416** [comment]
> 

hello ， I meet the same question. how did you sloved it finally?  （I tried to get the checkpoint by using “python ./src/main.py -c src/configs/sdn_sceneflow.config” . however, it seems some wrong in this code. the softlink are broken.）
