### ISSUE TITLE
Is the point cloud you uploaded processed by GDC?

### ISSUE THREAD

**Issue by Baboom-l** [mileyan/Pseudo_Lidar_V2#18]

**Comment by a-akram-98** [comment]
@Baboom-l Did you find out the solution, as I encountered the same issue the point cloud is distorted

**Comment by rsj007** [comment]
> @Baboom-l Did you find out the solution, as I encountered the same issue the point cloud is distorted

Me,too. Have you solved it?

**Comment by rsj007** [comment]
@Baboom-l Me,too. Have you solved it?

**Comment by Baboom-l** [comment]
The uploaded pseudo-point clouds are all generated by SDN. Point clouds are not GDC processed @rsj007

**Comment by rsj007** [comment]
I visisulize the uploaded point clouds using mayavi. The result looks not vey good. It has some distoration I circled in red and some tails behind the car. And it looks different from the one in paper. Do you know how to solve it?

![1145df43e212b73cf0f561e27fc23bf](https://user-images.githubusercontent.com/29651895/148223969-704f4767-f90d-47b3-b8a3-8a07a863a36a.png)
![image](https://user-images.githubusercontent.com/29651895/148224033-618b7d28-cebd-41ca-b9be-97f0f65b40f0.png)

**Comment by Baboom-l** [comment]
I have already answered in another issue[https://github.com/mileyan/Pseudo_Lidar_V2/issues/28](url)
